"""create favorites table

Revision ID: 181925e12bb8
Revises: b2c4f1a9d3e7
Create Date: 2026-06-16 10:11:52.525514

Story 3.7 — 즐겨찾기 도메인 테이블을 신규 생성한다(FR-10).

- **favorites**: ``id``(PK) · ``user_id``(FK users.id) · ``room_id``(FK rooms.id) ·
  ``created_at``(UTC timestamptz). 복합 UNIQUE ``uq_favorites_user_id_room_id``(사용자×룸 1행 —
  토글 멱등성의 DB 근거) + 단일 인덱스 ``idx_favorites_user_id``·``idx_favorites_room_id``.
- **FK ondelete 미지정(RESTRICT)**: rooms/users는 하드삭제하지 않는다(운영중단=is_active 비활성 E8).
- 제약명은 1.4 ``NAMING_CONVENTION`` 자동(PK/FK/INDEX) + 복합 UNIQUE 명시 단축명(회고 P1).

**라이브 DB 적용:** down_revision = 현재 head ``b2c4f1a9d3e7``. dev 완료 시 라이브 Supabase에
``uv run alembic upgrade head``를 실제 실행한다(메모 dev-workflow-policy-live-db-migration).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate가 sqlmodel.sql.sqltypes.* 타입을 렌더할 때 NameError 방지


# revision identifiers, used by Alembic.
revision: str = '181925e12bb8'
down_revision: Union[str, Sequence[str], None] = 'b2c4f1a9d3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_favorites_room_id_rooms')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorites')),
    sa.UniqueConstraint('user_id', 'room_id', name='uq_favorites_user_id_room_id')
    )
    op.create_index(op.f('idx_favorites_room_id'), 'favorites', ['room_id'], unique=False)
    op.create_index(op.f('idx_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('idx_favorites_room_id'), table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
