"""create document_chunks table

Revision ID: 7a6edff2b9ef
Revises: c9d3e5b7f1a4
Create Date: 2026-06-17 22:00:31.357623

Story 7.2 — 문서 RAG 데이터 계층 ``document_chunks`` 테이블을 신규 생성한다(FR-26 인프라).

- **document_chunks**(청크 1행/문서×청크): ``id``(PK) · ``source_path``(docs_corpus/ 상대 경로,
  조회 인덱스) · ``content_hash``(문서 sha256 — 멱등 기준, denormalize) · ``chunk_index``(문서 내
  순서) · ``content``(청크 원문) · ``embedding``(``vector(1536)`` — text-embedding-3-small) ·
  ``created_at``(UTC timestamptz). 복합 UNIQUE ``uq_document_chunks_source_path_chunk_index``
  (멱등 이중 방어) + 단일 인덱스 ``idx_document_chunks_source_path``.
- **HNSW 인덱스(수기 추가):** autogenerate는 opclass HNSW 인덱스를 만들지 못하므로 수기 추가한다
  (Dev Notes §함정 #2). ``idx_document_chunks_embedding_hnsw`` USING hnsw
  (``embedding`` ``vector_cosine_ops``) — 프로덕션 검색(7.5)은 코사인이라 스파이크 seed.sql과
  동일 연산자 클래스. ``downgrade``에 drop 대칭.
- **pgvector import(수기 추가):** autogenerate가 ``pgvector.sqlalchemy.vector.VECTOR``를 렌더하나
  import를 넣지 않아 ``NameError``가 난다(Dev Notes §함정 #1) → 상단에 ``import pgvector`` 추가.
- pgvector 확장은 baseline(``124a50c37b8c``)이 단독 소유한다 → 본 마이그레이션은 확장을 다시
  활성화하지 않는다(확장 의존만).
- 제약명은 1.4 ``NAMING_CONVENTION`` 자동(PK/INDEX) + 복합 UNIQUE 명시 단축명(회고 P1, 42자 ≤63).

**라이브 DB 적용:** down_revision = 현재 head ``c9d3e5b7f1a4``(review_replies, 5.6). dev 완료 시
라이브 Supabase에 ``uv run alembic upgrade head``를 실제 실행한다(메모 dev-workflow-policy-live-db-migration).
(참고: create-story 시점 명시 head ``a7c9e1b3d5f2``는 5.5/5.6 dev 이전 값 — 실제 head로 보정.)
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate가 sqlmodel.sql.sqltypes.* 타입을 렌더할 때 NameError 방지
import pgvector  # noqa: F401 — autogenerate가 렌더한 pgvector.sqlalchemy.vector.VECTOR의 NameError 방지


# revision identifiers, used by Alembic.
revision: str = '7a6edff2b9ef'
down_revision: Union[str, Sequence[str], None] = 'c9d3e5b7f1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('source_path', 'chunk_index', name='uq_document_chunks_source_path_chunk_index')
    )
    op.create_index(op.f('idx_document_chunks_source_path'), 'document_chunks', ['source_path'], unique=False)
    # ### end Alembic commands ###
    # HNSW 인덱스(수기 — autogenerate가 opclass 인덱스를 못 만든다). 코사인 연산자 클래스로
    # 프로덕션 검색 경로(7.5)와 통일(스파이크 seed.sql 선례).
    op.create_index(
        'idx_document_chunks_embedding_hnsw',
        'document_chunks',
        ['embedding'],
        postgresql_using='hnsw',
        postgresql_ops={'embedding': 'vector_cosine_ops'},
    )


def downgrade() -> None:
    """Downgrade schema."""
    # HNSW 인덱스 drop(수기 추가분 대칭 제거 — 테이블 drop 전에).
    op.drop_index('idx_document_chunks_embedding_hnsw', table_name='document_chunks')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_document_chunks_source_path'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
