"""create notifications table

Revision ID: a7c9e1b3d5f2
Revises: f1a2b3c4d5e6
Create Date: 2026-06-17 14:30:00.000000

Story 5.1 — 인앱 배너의 통합 ``notifications`` 테이블을 신규 생성한다(FR-18·18a 인프라).

- **notifications**(통지 1행/사용자×예약×종류): ``id``(PK) · ``user_id``(FK users.id) ·
  ``reservation_id``(FK reservations.id, **ondelete CASCADE** — 통지는 예약 종속 자식) ·
  ``type``(reservation_reminder/status_change) · ``reason``(nullable — 'rejected'|'cancelled') ·
  ``created_at``(UTC timestamptz) · ``dismissed_at``(nullable UTC timestamptz — NULL=미확인).
  복합 UNIQUE ``uq_notifications_user_reservation_type``(사용자·예약·종류당 1행 — 멱등 근거) +
  CHECK ``ck_notifications_type``(허용값 강제, 이중접두 아님) + 단일 인덱스
  ``idx_notifications_user_id``·``idx_notifications_reservation_id``.
- **FK ondelete:** users는 하드삭제 안 함(운영중단=is_active 비활성 E8) → 미지정(RESTRICT).
  ``reservation_id``만 CASCADE(통지는 예약 종속). 현 앱은 예약 하드삭제 경로 없음(취소=status
  flip)이라 CASCADE 실발현은 E8 — 의미상 종속을 스키마로 명시한다.
- 제약명은 1.4 ``NAMING_CONVENTION`` 자동(PK/FK/INDEX) + 복합 UNIQUE·CHECK 명시 단축명(회고 P1).
  가장 긴 FK 자동명 ``fk_notifications_reservation_id_reservations``=44자 ≤63 ✓. favorites
  마이그레이션(181925e12bb8) 스타일 미러.

**라이브 DB 적용:** down_revision = 현재 head ``f1a2b3c4d5e6``. dev 완료 시 라이브 Supabase에
``uv run alembic upgrade head``를 실제 실행한다(메모 dev-workflow-policy-live-db-migration).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate가 sqlmodel.sql.sqltypes.* 타입을 렌더할 때 NameError 방지


# revision identifiers, used by Alembic.
revision: str = 'a7c9e1b3d5f2'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type IN ('reservation_reminder', 'status_change')", name=op.f('ck_notifications_type')),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_notifications_reservation_id_reservations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('user_id', 'reservation_id', 'type', name='uq_notifications_user_reservation_type')
    )
    op.create_index(op.f('idx_notifications_reservation_id'), 'notifications', ['reservation_id'], unique=False)
    op.create_index(op.f('idx_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_reservation_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
