"""create reviews table

Revision ID: b8f2c4a6d9e3
Revises: a7c9e1b3d5f2
Create Date: 2026-06-17 16:00:00.000000

Story 5.5 — 이용 완료 예약의 별점+텍스트 후기 ``reviews`` 테이블을 신규 생성한다(FR-20·UJ-1).

- **reviews**(후기 1행/예약): ``id``(PK) · ``reservation_id``(FK reservations.id, **UNIQUE**
  ``uq_reviews_reservation`` — 예약당 1회, 중복 후기 차단의 진실의 원천) · ``room_id``(FK rooms.id,
  INDEX ``idx_reviews_room_id`` — 룸 상세 후기 목록 조회) · ``booker_id``(FK users.id, 소유권·
  has_review 합성) · ``rating``(int, CHECK ``ck_reviews_rating`` 1~5) · ``text``(VARCHAR(500) — KTH
  결정 2 텍스트 필수 1~500) · ``created_at``(UTC timestamptz).
- **FK ondelete:** 모두 **RESTRICT(미지정)** — 후기는 보존 데이터(작성 후 불변·수정/삭제 미제공),
  예약(취소=status flip)·룸·유저 하드삭제 경로 없음(운영중단=is_active 비활성 E8).
- 제약명은 1.4 ``NAMING_CONVENTION`` 자동(PK/FK/INDEX) + 단일컬럼 UNIQUE·CHECK 명시 단축명(회고 P1).
  가장 긴 FK 자동명 ``fk_reviews_reservation_id_reservations``=38자 ≤63 ✓. notifications
  마이그레이션(a7c9e1b3d5f2) 스타일 미러.

**라이브 DB 적용:** down_revision = 현재 head ``a7c9e1b3d5f2``(notifications). dev 완료 시 라이브
Supabase에 ``uv run alembic upgrade head``를 실제 실행한다(메모 dev-workflow-policy-live-db-migration).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate가 sqlmodel.sql.sqltypes.* 타입을 렌더할 때 NameError 방지


# revision identifiers, used by Alembic.
revision: str = 'b8f2c4a6d9e3'
down_revision: Union[str, Sequence[str], None] = 'a7c9e1b3d5f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('booker_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_reviews_rating')),
    sa.ForeignKeyConstraint(['booker_id'], ['users.id'], name=op.f('fk_reviews_booker_id_users')),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_reviews_reservation_id_reservations')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_reviews_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('reservation_id', name='uq_reviews_reservation')
    )
    op.create_index(op.f('idx_reviews_room_id'), 'reviews', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_reviews_room_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
