"""create review_replies table

Revision ID: c9d3e5b7f1a4
Revises: b8f2c4a6d9e3
Create Date: 2026-06-17 18:00:00.000000

Story 5.6 — 후기 1건에 대한 제공자 답글 ``review_replies`` 테이블을 신규 생성한다(FR-21·UJ-3).

- **review_replies**(답글 1행/후기): ``id``(PK) · ``review_id``(FK reviews.id, **UNIQUE**
  ``uq_review_replies_review`` — 후기당 1회, 중복 답글 차단의 진실의 원천) · ``provider_id``(FK
  users.id, 답글 작성자=룸 provider, 소유권 귀속) · ``text``(VARCHAR(500) — 후기 본문 상한 재사용
  1~500) · ``created_at``(UTC timestamptz).
- **FK ondelete:** 모두 **RESTRICT(미지정)** — 답글은 보존 데이터(작성 후 불변·수정/삭제 미제공),
  후기·유저 하드삭제 경로 없음(운영중단=is_active 비활성 E8).
- 제약명은 1.4 ``NAMING_CONVENTION`` 자동(PK/FK) + 단일컬럼 UNIQUE 명시 단축명(회고 P1). 가장 긴 FK
  자동명 ``fk_review_replies_provider_id_users``=39자 ≤63 ✓. **CHECK 없음**(별점 없음 — op.f()
  이중접두 함정 비해당). reviews 마이그레이션(b8f2c4a6d9e3) 스타일 미러.

**라이브 DB 적용:** down_revision = 현재 head ``b8f2c4a6d9e3``(reviews). dev 완료 시 라이브
Supabase에 ``uv run alembic upgrade head``를 실제 실행한다(메모 dev-workflow-policy-live-db-migration).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate가 sqlmodel.sql.sqltypes.* 타입을 렌더할 때 NameError 방지


# revision identifiers, used by Alembic.
revision: str = 'c9d3e5b7f1a4'
down_revision: Union[str, Sequence[str], None] = 'b8f2c4a6d9e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_replies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name=op.f('fk_review_replies_provider_id_users')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_review_replies_review_id_reviews')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_replies')),
    sa.UniqueConstraint('review_id', name='uq_review_replies_review')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_replies')
    # ### end Alembic commands ###
