"""create reservations tables

Revision ID: d8afe1726e81
Revises: 181925e12bb8
Create Date: 2026-06-16 13:52:28.141478

Story 4.1 — 예약 핵심 2테이블을 신규 생성한다(FR-15·16 기반, NFR-7).

- **reservations**(예약 단위, 1행/예약): ``id``(PK) · ``booker_id``(FK users.id) ·
  ``room_id``(FK rooms.id) · ``status``(confirmed/cancelled/rejected) · ``created_at``(UTC
  timestamptz). CHECK ``ck_reservations_status``(허용값 강제, 이중접두 아님) + 단일 인덱스
  ``idx_reservations_booker_id``·``idx_reservations_room_id``.
- **reservation_slots**(점유 행, N행/예약): ``id``(PK) · ``reservation_id``(FK reservations.id,
  **ondelete CASCADE** — 점유는 예약 종속 자식) · ``room_id``(FK rooms.id, denormalized) ·
  ``slot_start``(UTC timestamptz). **FULL 복합 UNIQUE ``uq_reservation_slots_room_slot``**
  (한 룸·한 슬롯에 활성 점유 최대 1행 = 중복·부분 점유 0의 진실의 원천). 취소/거절 시 점유 행을
  DELETE하므로 활성 점유만 잔존 → 부분 인덱스 불요(FULL UNIQUE로 충분).
- **FK ondelete:** users/rooms는 하드삭제 안 함(운영중단=is_active 비활성 E8) → 미지정(RESTRICT).
  ``reservation_slots.reservation_id``만 CASCADE.
- 제약명은 1.4 ``NAMING_CONVENTION`` 자동(PK/FK/INDEX) + 복합 UNIQUE·CHECK 명시 단축명(회고 P1).
  deferred L71(1.4 — "63자 한계, 트리거=4.1 복합 UNIQUE")을 본 스토리에서 회수: 가장 긴 FK 자동명
  ``fk_reservation_slots_reservation_id_reservations``=48자 ≤63 ✓.

**라이브 DB 적용:** down_revision = 현재 head ``181925e12bb8``. dev 완료 시 라이브 Supabase에
``uv run alembic upgrade head``를 실제 실행한다(메모 dev-workflow-policy-live-db-migration).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate가 sqlmodel.sql.sqltypes.* 타입을 렌더할 때 NameError 방지


# revision identifiers, used by Alembic.
revision: str = 'd8afe1726e81'
down_revision: Union[str, Sequence[str], None] = '181925e12bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booker_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('confirmed', 'cancelled', 'rejected')", name=op.f('ck_reservations_status')),
    sa.ForeignKeyConstraint(['booker_id'], ['users.id'], name=op.f('fk_reservations_booker_id_users')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_reservations_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations'))
    )
    op.create_index(op.f('idx_reservations_booker_id'), 'reservations', ['booker_id'], unique=False)
    op.create_index(op.f('idx_reservations_room_id'), 'reservations', ['room_id'], unique=False)
    op.create_table('reservation_slots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('slot_start', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_reservation_slots_reservation_id_reservations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_reservation_slots_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation_slots')),
    sa.UniqueConstraint('room_id', 'slot_start', name='uq_reservation_slots_room_slot')
    )
    op.create_index(op.f('idx_reservation_slots_reservation_id'), 'reservation_slots', ['reservation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_reservation_slots_reservation_id'), table_name='reservation_slots')
    op.drop_table('reservation_slots')
    op.drop_index(op.f('idx_reservations_room_id'), table_name='reservations')
    op.drop_index(op.f('idx_reservations_booker_id'), table_name='reservations')
    op.drop_table('reservations')
    # ### end Alembic commands ###
